### ISSUE TITLE
候选词数量异常

### ISSUE THREAD

**Issue by tumuyan** [huaxianyan/Rime#4]
使用原输入方案，键入声母n或m，候选词会满屏（单字），但是添加此项目的客制化方案后，键入声母n或m只有2-3个候选词。 进一步输入韵母后，候选词数量恢复正常

**Comment by huaxianyan** [comment]
之前版本我把只有 m 以及 ng 那些从词典里剔除了，考虑到不常用并且影响选字。

新版配置删除了从袖珍拼音简化字方案复制并经过剔除的词库，直接用方案原本的词库文件，所以会有此问题。

**Comment by huaxianyan** [comment]
@tumuyan 更新了一版，剔除了那些会引起候选列表问题的字词

**Comment by tumuyan** [comment]
是的，新版没有这样的问题了。  
但是我觉得更奇怪了...使用之前的版本，按下m时，候选词只有 “呣 嘸 呒”三个生僻字没有其他候选词了。按下韵母后（比如ma会出现ma读音的常用字）这说明，ma读音的常用字在词典中；因此在按下m时，ma读音的高频字也show出来才对啊？  

> @tumuyan 更新了一版，剔除了那些会引起候选列表问题的字词

**Comment by huaxianyan** [comment]
@tumuyan 我之前发现这个情况的时候，猜测是 Rime 发现词库中有完全符合键入内容的字时，会只显示这些候选。

其实你输入 ``man`` 的时候，仔细看也会发现没有 ``mang`` 的候选，只是一般这个时候我们几乎不会注意到它，不影响使用。

这只是我的猜测，不一定对，不过单声母字这种现象确实影响体验，综合考虑还是剔除了。

**Comment by tumuyan** [comment]
@huaxianyan 很有道理！我很久之前发现打xin不出现xing候选词的时候，单纯想，输入法强制区分前后鼻音，这也ok，提升普通话水平嘛。现在看应该是同个原因。
